### ISSUE TITLE
Please add our CVPR2024 paper MP5: A Multi-modal Open-ended Embodied Agent

### ISSUE THREAD

**Issue by IranQin** [amusi/CVPR2024-Papers-with-Code#214]
Name: MP5: A Multi-modal Open-ended Embodied System in Minecraft via Active Perception
Paper: https://arxiv.org/abs/2312.07472
Code: https://github.com/IranQin/MP5
Website: https://iranqin.github.io/MP5.github.io/

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
