### ISSUE TITLE
share CVPR2024 LEMON: Learning 3D Human-Object Interaction Relation from 2D Images

### ISSUE THREAD

**Issue by yyvhang** [amusi/CVPR2024-Papers-with-Code#217]
Paper name/title: LEMON: Learning 3D Human-Object Interaction Relation from 2D Images (Embodied AI)
Paper link: https://arxiv.org/abs/2312.08963
project page: https://yyvhang.github.io/LEMON/
Code link: https://github.com/yyvhang/lemon_3d

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
