### ISSUE TITLE
Please add the new paper

### ISSUE THREAD

**Issue by Championchess** [amusi/CVPR2024-Papers-with-Code#219]
Amodal Ground Truth and Completion in the Wild 
Guanqi Zhan, Chuanxia Zheng, Weidi Xie, Andrew Zisserman

Paper: https://arxiv.org/pdf/2312.17247.pdf
Code: https://github.com/Championchess/Amodal-Completion-in-the-Wild
Homepage: https://www.robots.ox.ac.uk/~vgg/research/amodal/

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
