### ISSUE TITLE
Please add a new paper, thanks!

### ISSUE THREAD

**Issue by BIT-MJY** [amusi/CVPR2024-Papers-with-Code#221]
Name: Cam4DOcc: Benchmark for Camera-Only 4D Occupancy Forecasting in Autonomous Driving Applications
Paper: https://arxiv.org/abs/2311.17663
Code: https://github.com/haomo-ai/Cam4DOcc

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
