### ISSUE TITLE
Please add a paper

### ISSUE THREAD

**Issue by ZPDu** [amusi/CVPR2024-Papers-with-Code#222]
Many thanks for aggregating the papers. Could you please add our paper at CVPR 2024:
Title: Boosting Object Detection with Zero-Shot Day-Night Domain Adaptation
Paper link: https://arxiv.org/abs/2312.01220
Code link: https://github.com/ZPDu/Boosting-Object-Detection-with-Zero-Shot-Day-Night-Domain-Adaptation

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
