### ISSUE TITLE
Introducing 4 CVPR 2024 papers of ours

### ISSUE THREAD

**Issue by npurson** [amusi/CVPR2024-Papers-with-Code#223]
1. **4D Gaussian Splatting for Real-Time Dynamic Scene Rendering**
     * **Subject:** 3D GS
     * **Paper:** https://arxiv.org/abs/2310.08528
     * **Code:** https://github.com/hustvl/4DGaussians

2. **GaussianDreamer: Fast Generation from Text to 3D Gaussians by Bridging 2D and 3D Diffusion Models**
     * **Subject:** 3D GS
     * **Paper:** https://arxiv.org/abs/2310.08529
     * **Code:** https://github.com/hustvl/GaussianDreamer

3. **YOLO-World: Real-Time Open-Vocabulary Object Detection**
     * **Subject:** Object Detection (Open-World)
     * **Paper:** https://arxiv.org/abs/2401.17270
     * **Code:** https://github.com/AILab-CVC/YOLO-World

4. **Symphonize 3D Semantic Scene Completion with Contextual Instance Queries**
     * **Subject:** 3D Semantic Scene Completion (3D Scene Occupancy Prediction)
     * **Paper:** https://arxiv.org/abs/2306.15670
     * **Code:** https://github.com/hustvl/Symphonies

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
