### ISSUE TITLE
please add a paper, thanks!

### ISSUE THREAD

**Issue by Junda24** [amusi/CVPR2024-Papers-with-Code#226]
Many thanks for aggregating the papers. Could you please add our paper at CVPR 2024:
Paper name: Adaptive Fusion of Single-View and Multi-View Depth for Autonomous Driving
Paper link: https://arxiv.org/pdf/2403.07535.pdf
Code link: https://github.com/Junda24/AFNet

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
