### ISSUE TITLE
Please add a paper

### ISSUE THREAD

**Issue by chenshuang-zhang** [amusi/CVPR2024-Papers-with-Code#228]
Thanks for the awesome repository! Could you please add our paper as follows? Thank you!

**Title:** ImageNet-D: Benchmarking Neural Network Robustness on Diffusion Synthetic Object
**Homepage:** https://chenshuang-zhang.github.io/imagenet_d/
**Paper:** https://arxiv.org/abs/2403.18775
**Code:** https://github.com/chenshuang-zhang/imagenet_d

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
