### ISSUE TITLE
Please add our work to Visual Tracking and Long-Tail.

### ISSUE THREAD

**Issue by chen-si-jia** [amusi/CVPR2024-Papers-with-Code#230]
Paper name/title: Delving into the Trajectory Long-tail Distribution for Muti-object Tracking
Paper link: https://arxiv.org/abs/2403.04700
Code link: https://github.com/chen-si-jia/Trajectory-Long-tail-Distribution-for-MOT

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
