### ISSUE TITLE
Please add new papers about 多模态大语言模型(MLLM),  fairness learning, and anomaly detection  

### ISSUE THREAD

**Issue by tianyu0207** [amusi/CVPR2024-Papers-with-Code#231]
**FairCLIP: Harnessing Fairness in Vision-Language Learning**

Paper Link: https://arxiv.org/abs/2403.19949
Code Link: https://github.com/Harvard-Ophthalmology-AI-Lab/FairCLIP

another paper on Anomaly Detection: **Anomaly Heterogeneity Learning for Open-set Supervised Anomaly Detection**

Paper Link: https://arxiv.org/abs/2310.12790
Code Link: https://github.com/mala-lab/AHL

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
